name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code cloned from github"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build Docker Container
        run: echo "testing container"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
