name: Hello

on:
  push:
    branches: [main]

# these are jobs inside the workflow
jobs:
  # this is the name of the job
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name: say hello to username
        run: echo "Hello $USER"
  details:
    runs-on: ubuntu-latest
    steps: 
      - name: show version of docker
        run: docker --version && python --version
